name: ci
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: codecov/codecov-action@v4
      - uses: sigstore/cosign-installer@v3.5.0
      - uses: psf/black@stable
      - uses: helm/chart-releaser-action@v1.6.0
      - uses: tj-actions/changed-files@v44
      - uses: chainguard-actions/setup-ko@v0.7.0
